version: '3.8'

services:
  web:
    build: .
    container_name: django_ia_desk
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./files_storage:/app/files_storage
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
